# Generated by Django 4.2.7 on 2023-12-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_seller_user_seller_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('address', models.TextField(default='No Address')),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(default='No email', max_length=254),
        ),
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default='No password', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='pincode',
            field=models.CharField(default='No Pincode', max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='contact_number',
            field=models.CharField(default='No number', max_length=20),
        ),
    ]
